// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yswqfdgqgafbacywxall.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlzd3FmZGdxZ2FmYmFjeXd4YWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODM5MDYsImV4cCI6MjA2NTA1OTkwNn0.V7mX2jiUn4lD6PhwB2aEp4xiah1LWTZ97977JL3KLn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);